pipeline:
  name: testpipe3
  identifier: testpipe3
  tags: {}
  projectIdentifier: satyamtest
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: githubconnector
        build: <+input>
  stages:
    - stage:
        name: build-and-push
        identifier: buildandpush
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: kubernetesclusterconnector
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: build-jar-file
                  identifier: buildjarfile
                  spec:
                    connectorRef: dockerregistryconnector
                    image: maven:3.9-eclipse-temurin-17
                    shell: Sh
                    command: mvn clean package
                  description: build jar file before publishing the artifact to docker registry
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerregistryconnector
                    repo: thakursatyam1104/satyam-kumar-thakur-test
                    tags:
                      - default
                    caching: true
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: booknestservice
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
            gitBranch: main
          environment:
            environmentRef: localdev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: deploymentinfrastructure
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
